name: Workflow 0
on: [push]
jobs:
  job_0:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: 'mhagger/git-test'
          path: '.git-test'
      - run: tree -a .
      - run: echo "PATH=${PATH}:$(pwd)/.git-test/bin" >> "${GITHUB_ENV}"
      - run: git test help && git test add './test.sh'
      - run: git test run --keep-going
      - run: tree -a .
      # - run: git fetch origin 'refs/notes/*:refs/notes/*'
      # - run: git notes --ref 'notes/beep/boop' | awk '{ print $2 }' | xargs -n1 git notes --ref 'notes/beep/boop' show

